In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

In [32]:
# 1. Dataset dari slide Stanford
corpus = [
    "Sudarto menegaskan alumni LPDP yang tidak patuh akan dikenakan sanksi sosial berupa publikasi nama di website resmi.",  # Doc 0 — sanksi
    "Sudarto menekankan dana yang digunakan membiayai pendidikan alumni merupakan uang rakyat yang berasal dari pajak.",      # Doc 1 — kebijakan
    "Penerima beasiswa LPDP wajib kembali ke Indonesia, alumni LPDP harus mengabdi kepada negara setelah menyelesaikan studi." # Doc 2 — kewajiban
]

# 2. Representasi Vektor (Hanya fokus pada kata 'alumni' dan 'lpdp')
vectorizer = CountVectorizer(vocabulary=['alumni', 'lpdp'])
X = vectorizer.fit_transform(corpus)

In [33]:
# Cek kata yang muncul di corpus
for i, doc in enumerate(corpus):
    words = set(doc.lower().replace(',', '').replace('.', '').split())
    print(f'Doc {i}: {sorted(words)}')

Doc 0: ['akan', 'alumni', 'berupa', 'di', 'dikenakan', 'lpdp', 'menegaskan', 'nama', 'patuh', 'publikasi', 'resmi', 'sanksi', 'sosial', 'sudarto', 'tidak', 'website', 'yang']
Doc 1: ['alumni', 'berasal', 'dana', 'dari', 'digunakan', 'membiayai', 'menekankan', 'merupakan', 'pajak', 'pendidikan', 'rakyat', 'sudarto', 'uang', 'yang']
Doc 2: ['alumni', 'beasiswa', 'harus', 'indonesia', 'ke', 'kembali', 'kepada', 'lpdp', 'mengabdi', 'menyelesaikan', 'negara', 'penerima', 'setelah', 'studi', 'wajib']

In [35]:
vectorizer = CountVectorizer(vocabulary=['alumni', 'lpdp'])
X = vectorizer.fit_transform(corpus)

df_vec = pd.DataFrame(
    X.toarray(),
    columns=['alumni', 'lpdp'],
    index=['Doc 0 (sanksi)', 'Doc 1 (kebijakan)', 'Doc 2 (kewajiban)']
)

print('=== MATRIKS VEKTOR (CountVectorizer) ===')
print('Vocabulary: ["alumni", "lpdp"]\n')
display(df_vec)

=== MATRIKS VEKTOR (CountVectorizer) ===
Vocabulary: ["alumni", "lpdp"]

                   alumni  lpdp
Doc 0 (sanksi)          1     1
Doc 1 (kebijakan)       1     0
Doc 2 (kewajiban)       1     2

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

# 1. Dataset dari topik lpdp
corpus = [
    "Sudarto menegaskan alumni LPDP yang tidak patuh akan dikenakan sanksi sosial berupa publikasi nama di website resmi.",  # Doc 0 — sanksi
    "Sudarto menekankan dana yang digunakan membiayai pendidikan alumni merupakan uang rakyat yang berasal dari pajak.",      # Doc 1 — kebijakan
    "Penerima beasiswa LPDP wajib kembali ke Indonesia, alumni LPDP harus mengabdi kepada negara setelah menyelesaikan studi." # Doc 2 — kewajiban
]

# 2. Representasi Vektor (Hanya fokus pada kata 'alumni' dan 'lpdp')
vectorizer = CountVectorizer(vocabulary=['alumni', 'lpdp'])
X = vectorizer.fit_transform(corpus)

# 3. Hitung Cosine Similarity
# Membandingkan semua dokumen dengan Dokumen 0 (1 sanksi)
cos_sim = cosine_similarity(X[0:1], X)

# Tampilkan Hasil
df = pd.DataFrame(X.toarray(), columns=['alumni', 'lpdp'])
df['Cosine Sim to Doc 0'] = cos_sim.flatten()
print(df)

   alumni  lpdp  Cosine Sim to Doc 0
0       1     1             1.000000
1       1     0             0.707107
2       1     2             0.948683

**CountVectorizer:** Mengubah teks menjadi angka (matriks frekuensi kata). Di sini kita membatasi fitur hanya pada kata "alumni" dan "lpdp" agar sesuai dengan grafik di slide Stanford.

**Cosine Similarity vs Distance:** Fungsi ini menghasilkan nilai 0 sampai 1. Semakin mendekati 1, semakin mirip kedua dokumen tersebut.

**Analisis Hasil:** Bahwa Dokumen 2 (kewajiban) memiliki nilai similarity yang tinggi terhadap Dokumen 0, membuktikan bahwa meskipun jumlah katanya jauh lebih banyak, "arah" topiknya tetap serupa.

In [37]:
import re

# Derive documents dari corpus (hapus tanda baca & lowercase)
documents = [re.sub(r'[^\w\s]', '', doc.lower()) for doc in corpus]

# Tampilkan
for i, doc in enumerate(documents):
    print(f'Doc {i}: {doc}')

Doc 0: sudarto menegaskan alumni lpdp yang tidak patuh akan dikenakan sanksi sosial berupa publikasi nama di website resmi
Doc 1: sudarto menekankan dana yang digunakan membiayai pendidikan alumni merupakan uang rakyat yang berasal dari pajak
Doc 2: penerima beasiswa lpdp wajib kembali ke indonesia alumni lpdp harus mengabdi kepada negara setelah menyelesaikan studi

In [38]:
import pandas as pd
from collections import Counter
tf = pd.DataFrame(
[Counter(doc.split()) for doc in documents],
).fillna(0)
tf

,sudarto,menegaskan,alumni,lpdp,yang,tidak,patuh,akan,dikenakan,sanksi,...,kembali,ke,indonesia,harus,mengabdi,kepada,negara,setelah,menyelesaikan,studi
0,1.0,1.0,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,1,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [39]:
import numpy as np
def length(v):
    return np.sqrt((v ** 2).sum())
def cos_dist(v, w):
    return 1 - (v * w).sum() / (length(v) * length(w))
cos_dist(tf.loc[0], tf.loc[1]), cos_dist(tf.loc[0], tf.loc[2])

(np.float64(0.7647058823529411), np.float64(0.8285014148574912))

In [40]:
import pandas as pd
from collections import Counter

# Data dari slide
documents = [
    "alumni lpdp",                              # Doc 0 — sanksi
    "alumni",                                          # Doc 1 — kebijakan
    "alumni lpdp lpdp"     # Doc 2 - kewajiban
]

# Membuat DataFrame TF secara manual
tf = pd.DataFrame(
    [Counter(doc.split()) for doc in documents],
).fillna(0).astype(int)

# Menampilkan matriks
print("Matriks Term Frequency (TF):")
print(tf)

Matriks Term Frequency (TF):
   alumni  lpdp
0       1     1
1       1     0
2       1     2

In [41]:
full_cos_sim_matrix = cosine_similarity(X)

# Display the full matrix as a DataFrame for better readability
cos_sim_df = pd.DataFrame(full_cos_sim_matrix, index=[f'Doc {i}' for i in range(len(corpus))], columns=[f'Doc {i}' for i in range(len(corpus))])
print("Full Cosine Similarity Matrix:")
print(cos_sim_df)

Full Cosine Similarity Matrix:
          Doc 0     Doc 1     Doc 2
Doc 0  1.000000  0.707107  0.948683
Doc 1  0.707107  1.000000  0.447214
Doc 2  0.948683  0.447214  1.000000

**Summary**
Doc 0 dan Doc 2 berada paling dekat satu sama lain karena membicarakan hal yang paling berkaitan — yaitu konsekuensi (sanksi) dan dasar hukumnya (kewajiban alumni LPDP). Doc 1 berdiri lebih sendiri karena hanya membahas alasan kebijakan dari sisi pendanaan pajak tanpa menyebut LPDP secara eksplisit.